# Generated by Django 5.2.8 on 2026-01-23 09:56
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
