# Generated by Django 6.0.1 on 2026-01-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_user_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_like',
            new_name='users_like',
        ),
    ]
