# Generated by Django 6.0.1 on 2026-02-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginToken',
        ),
    ]
